doc/design.md
doc/system_requirements.md
src/main/java/openfasttrack/cli/CommandLineInterpreter.java
src/test/java/openfasttrack/cli/TestCommandLineInterpreter.java

Please check review changes and merge.

Review of #5

---

pom.xml
src/main/java/openfasttrack/cli/CliArguments.java
src/main/java/openfasttrack/cli/CliStarter.java
src/main/java/openfasttrack/cli/CommandLineInterpreter.java
src/main/java/openfasttrack/cli/MissingArgumentException.java
src/main/java/openfasttrack/cli/commands/ConvertCommand.java
src/main/java/openfasttrack/cli/commands/TraceCommand.java
src/main/java/openfasttrack/exporter/ExporterFactory.java
src/main/java/openfasttrack/exporter/ExporterFactoryLoader.java
src/main/java/openfasttrack/exporter/ExporterService.java
src/main/java/openfasttrack/exporter/specobject/SpecobjectExporterFactory.java
src/main/java/openfasttrack/importer/ImporterFactoryLoader.java
src/main/java/openfasttrack/importer/ImporterService.java
src/main/java/openfasttrack/importer/MultiFileImporter.java
src/main/java/openfasttrack/importer/SpecificationMapListBuilder.java
src/main/java/openfasttrack/importer/specobject/ImportHelper.java
src/main/java/openfasttrack/report/ReportService.java
src/test/java/openfasttrack/cli/TestCliStarter.java
src/test/java/openfasttrack/cli/TestCommandLineInterpreter.java
src/test/resources/logging.properties

Create a command line interface providing commands `trace` and `convert`.

Command line interface

---

pom.xml
src/main/java/openfasttrack/cli/CliArguments.java
src/main/java/openfasttrack/cli/CliStarter.java
src/main/java/openfasttrack/cli/CommandLineInterpreter.java
src/main/java/openfasttrack/cli/MissingArgumentException.java
src/main/java/openfasttrack/cli/commands/ConvertCommand.java
src/main/java/openfasttrack/cli/commands/TraceCommand.java
src/main/java/openfasttrack/exporter/ExporterFactoryLoader.java
src/main/java/openfasttrack/exporter/specobject/SpecobjectExporterFactory.java
src/main/java/openfasttrack/importer/ImporterFactoryLoader.java
src/main/java/openfasttrack/importer/ImporterService.java
src/main/java/openfasttrack/importer/MultiFileImporter.java
src/main/java/openfasttrack/importer/SpecificationListBuilder.java
src/main/java/openfasttrack/importer/SpecificationMapListBuilder.java
src/main/java/openfasttrack/importer/specobject/ImportHelper.java
src/main/java/openfasttrack/report/ReportService.java
src/test/java/openfasttrack/cli/TestCliStarter.java
src/test/java/openfasttrack/cli/TestCommandLineInterpreter.java
src/test/java/openfasttrack/exporter/specobject/TestSpecobjectExporter.java
src/test/java/openfasttrack/importer/TestImporterService.java
src/test/java/openfasttrack/importer/TestSpecificationItemListBuilder.java
src/test/java/openfasttrack/importer/TestSpecificationListBuilder.java
src/test/java/openfasttrack/importer/specobject/TestSpecobjectImporter.java
src/test/java/openfasttrack/importer/tag/TestTagImporter.java
src/test/resources/logging.properties

#23 Allow duplicate ids during import

---

Jenkinsfile
pom.xml

This adds a `Jenkinsfile` that configures a build pipeline for Jenkins 2.

Add Jenkinsfile for mvn build

---

Jenkinsfile
pom.xml
src/main/java/openfasttrack/importer/specobject/ImportHelper.java
src/main/java/openfasttrack/importer/specobject/SingleSpecobjectImportHelper.java
src/test/java/openfasttrack/exporter/specobject/TestSpecobjectExporter.java
src/test/java/openfasttrack/importer/specobject/TestSpecobjectImporter.java
src/test/resources/specobject/specobject-without-doctype.xml

Skip files with unknown root element. See #34

#34 Whitelist XML root elements

---

src/main/java/openfasttrack/importer/ImporterFactory.java
src/main/java/openfasttrack/importer/markdown/MarkdownImporter.java
src/main/java/openfasttrack/importer/markdown/MarkdownImporterFactory.java
src/main/java/openfasttrack/importer/specobject/ImportHelper.java
src/main/java/openfasttrack/importer/specobject/SpecobjectImporter.java
src/main/java/openfasttrack/importer/specobject/SpecobjectImporterFactory.java
src/main/java/openfasttrack/importer/tag/TagImporter.java
src/main/java/openfasttrack/importer/tag/TagImporterFactory.java
src/test/java/openfasttrack/exporter/specobject/TestSpecobjectExporter.java
src/test/java/openfasttrack/importer/markdown/TestImportMarkdown.java
src/test/java/openfasttrack/importer/specobject/TestSpecobjectImporter.java
src/test/java/openfasttrack/importer/tag/TestTagImporter.java

Add filename to importers and log it where possible

---

src/main/java/openfasttrack/importer/markdown/MdPattern.java
src/test/java/openfasttrack/importer/markdown/TestImportMarkdown.java

Task-Url: https://github.com/hamstercommunity/openfasttrack/issues/50

50: Markdown importer ignores single "needs"

---

src/main/java/openfasttrack/importer/tag/TagImporter.java
src/test/java/openfasttrack/importer/tag/TestTagImporter.java

TagImporter generates covers attribute

---

src/main/java/openfasttrack/cli/commands/AbstractCommand.java
src/main/java/openfasttrack/cli/commands/ConvertCommand.java
src/main/java/openfasttrack/cli/commands/TraceCommand.java
src/main/java/openfasttrack/core/LinkedItemIndex.java
src/main/java/openfasttrack/exporter/ExporterFactory.java
src/main/java/openfasttrack/exporter/ExporterService.java
src/main/java/openfasttrack/exporter/specobject/SpecobjectExporter.java
src/main/java/openfasttrack/exporter/specobject/SpecobjectExporterFactory.java
src/main/java/openfasttrack/report/PlainTextReport.java
src/test/java/openfasttrack/cli/TestCliStarter.java
src/test/java/openfasttrack/exporter/specobject/TestSpecobjectExporter.java
src/test/java/openfasttrack/matcher/MultilineTextMatcher.java
src/test/java/openfasttrack/report/TestPlainTextReport.java

Task-Url: https://github.com/hamstercommunity/openfasttrack/issues/56

56: CLI "trace" skips linking step

---

src/main/java/openfasttrack/importer/tag/TagImporter.java
src/test/java/openfasttrack/importer/tag/TestTagImporter.java

#59 Add covered item name to generated name

---

doc/usage.txt
src/main/java/openfasttrack/cli/CliArguments.java
src/test/java/openfasttrack/cli/TestCliArguments.java
src/test/java/openfasttrack/cli/TestCliStarter.java

Task-Url: https://github.com/hamstercommunity/openfasttrack/issues/58

58: Added integration test, CLI options and usage file.

---

doc/design.md
src/main/java/org/itsallcode/openfasttrace/cli/CliArguments.java
src/main/java/org/itsallcode/openfasttrace/mode/ConvertMode.java
src/test/java/org/itsallcode/openfasttrace/cli/TestCliArguments.java
src/test/java/org/itsallcode/openfasttrace/cli/TestCliStarter.java

Task-Url: https://github.com/hamstercommunity/openfasttrack/issues/103

103: Found no matching exporter for output format

---

src/main/java/org/itsallcode/openfasttrace/Converter.java
src/main/java/org/itsallcode/openfasttrace/Reporter.java
src/main/java/org/itsallcode/openfasttrace/cli/ArgumentValidator.java
src/main/java/org/itsallcode/openfasttrace/cli/CliStarter.java
src/main/java/org/itsallcode/openfasttrace/core/LinkedSpecificationItem.java
src/main/java/org/itsallcode/openfasttrace/core/Linker.java
src/main/java/org/itsallcode/openfasttrace/core/Location.java
src/main/java/org/itsallcode/openfasttrace/core/SpecificationItem.java
src/main/java/org/itsallcode/openfasttrace/core/xml/ContentHandlerAdapter.java
src/main/java/org/itsallcode/openfasttrace/core/xml/tree/CallbackContentHandler.java
src/main/java/org/itsallcode/openfasttrace/importer/legacytag/LegacyTagImporterFactory.java

Task-Url: https://github.com/hamstercommunity/openfasttrack/issues/107

107: Fixed major findings. Tried "Generated" annotation.

---

src/test/java/org/itsallcode/openfasttrace/exporter/specobject/TestSpecobjectExporter.java
src/test/java/org/itsallcode/openfasttrace/importer/legacytag/TestLegacyTagImporterFactory.java

#119 Fix unit test under windows

---

README.md

Task-Url: https://github.com/hamstercommunity/openfasttrack/issues/125

125: Separate runtime and build time dependencies

---

.travis.yml
pom.xml
src/test/java/org/itsallcode/openfasttrace/importer/legacytag/config/DescribedPathMatcherTest.java
src/test/java/org/itsallcode/openfasttrace/testutil/OsDetector.java

See #119 
Deactivated sonar will be re-enabled in #134

Fix tests under Windows

---

doc/system_requirements.md
src/main/java/org/itsallcode/openfasttrace/importer/markdown/MarkdownImporter.java
src/main/java/org/itsallcode/openfasttrace/importer/markdown/MdPattern.java
src/test/java/org/itsallcode/openfasttrace/importer/markdown/TestImportMarkdown.java

Fixed the self-trace ahead of the presentation at a big company.
@kaklakariada, could you please check the PR and build release 0.5.4 in case everything is fine.
I will base my presentation on 0.5.4 then.

#138: Fixed broken trace.

---

.travis.yml
pom.xml
src/test/java/org/itsallcode/openfasttrace/core/serviceloader/TestInitializingServiceLoader.java

A test failed with Java 10, see commit 27a2bb9778f943b190617d35f92365075905a9ad.
This pr also runs the tests with java 10.

Test with java10

---

README.md
pom.xml

See https://github.com/itsallcode/junit5-system-extensions/pull/10/files

Update bintray repo name

---

src/main/java/org/itsallcode/openfasttrace/report/view/html/OriginLinkFormatter.java
src/test/java/org/itsallcode/openfasttrace/report/view/html/TestOriginLinkFormatter.java

Fix unit test under windows

---

README.md
src/main/java/org/itsallcode/openfasttrace/ReportSettings.java
src/main/java/org/itsallcode/openfasttrace/core/xml/tree/CallbackContentHandler.java
src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java
src/main/java/org/itsallcode/openfasttrace/report/view/html/MarkdownLineStateMachine.java
src/main/java/org/itsallcode/openfasttrace/report/view/html/MarkdownLineTransition.java
src/test/java/org/itsallcode/openfasttrace/testutil/AbstractFileBasedTest.java

* Fix sonar badges and links after sonar project was deleted
* Fix sonar analysis warnings

Fix sonarcloud issues

---

doc/user_guide.md

Just read through the document, and found a bunch of wording and typo mistakes.

Wording and typos in user guide

---

parent/pom.xml

Upgrade test and build dependencies to latest stable versions

Upgrade dependencies

---

doc/usage.txt
oft

#245 Fix command line usage in documentation

---

doc/CHANGELOG.md
importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java
importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterFactory.java

#270: Added support for jvm languages: Clojure, Kotlin, Scala

---

api/src/main/java/org/itsallcode/openfasttrace/api/importer/MultiFileImporter.java
core/src/main/java/org/itsallcode/openfasttrace/core/importer/ImporterFactoryLoader.java
core/src/main/java/org/itsallcode/openfasttrace/core/importer/MultiFileImporterImpl.java
core/src/test/java/org/itsallcode/openfasttrace/core/importer/TestImporterFactoryLoader.java
core/src/test/java/org/itsallcode/openfasttrace/core/importer/TestImporterService.java
core/src/test/java/org/itsallcode/openfasttrace/core/importer/TestMultiFileImporter.java
importer/zip/src/main/java/org/itsallcode/openfasttrace/importer/zip/ZipFileImporter.java

Handling of files for which no importer (or too many) is present does not fail with an exception

---

.codecov.yml
Jenkinsfile
README.md
doc/CHANGELOG.md
doc/developer_guide.md
parent/pom.xml

This prepares for the 3.2.0 release and removes some unused files.
The next release includes the following PR:
* #261 
* #258

Prepare release 3.2.0

---

doc/CHANGELOG.md
parent/pom.xml

#310 Upgrade dependencies

---

doc/CHANGELOG.md
doc/spec/design.md
importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/LongTagImportingLineConsumer.java
importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporter.java

#315: Use readable names for tags with needed coverage

---

doc/CHANGELOG.md
exporter/specobject/src/main/java/module-info.java
importer/markdown/src/main/java/module-info.java
importer/specobject/src/main/java/module-info.java
importer/tag/src/main/java/module-info.java
importer/zip/src/main/java/module-info.java
product/src/test/java/org/itsallcode/openfasttrace/TestAllServicesAvailable.java
reporter/aspec/src/main/java/module-info.java
reporter/html/src/main/java/module-info.java
reporter/plaintext/src/main/java/module-info.java

#336: Add provides tag for services

---

doc/CHANGELOG.md
parent/pom.xml
product/src/test/java/org/itsallcode/openfasttrace/ITestSelfTrace.java
product/src/test/java/org/itsallcode/openfasttrace/mode/AbstractOftTest.java
product/src/test/java/org/itsallcode/openfasttrace/mode/ITestOftAsConverter.java
product/src/test/java/org/itsallcode/openfasttrace/mode/ITestOftAsReporter.java
reporter/html/src/main/java/org/itsallcode/openfasttrace/report/html/view/html/OriginLinkFormatter.java
reporter/html/src/test/java/org/itsallcode/openfasttrace/report/html/view/html/TestOriginLinkFormatter.java
testutil/src/main/java/org/itsallcode/openfasttrace/testutil/OsCheck.java
testutil/src/main/java/org/itsallcode/openfasttrace/testutil/OsDetector.java
testutil/src/test/java/org/itsallcode/openfasttrace/testutil/OsCheckTest.java

#308: Fix running tests under macOS

---

.github/workflows/build.yml
doc/CHANGELOG.md
oft
oft-self-trace.sh
product/src/test/java/org/itsallcode/openfasttrace/cli/TestCliStarter.java

Closes #340
PR https://github.com/itsallcode/openfasttrace/pull/339 fixes failing tests. Merge it before reviewing this.

#340: Added CI build for macOS and Windows

---

.github/workflows/broken_links_checker.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.vscode/extensions.json
CONTRIBUTING.md
doc/CHANGELOG.md
doc/developer_guide.md
oft-self-trace.sh
parent/pom.xml
product/pom.xml

Closes #341
This also updates the instructions for self-tracing.

#341 Rename main branch

---

.github/workflows/build.yml
.vscode/settings.json
parent/pom.xml
pom.xml

This upgrades dependencies and plugins and adds tests with Java 21.

Fix sonar build

---

README.md
doc/developer_guide.md

Improved the link section of the readme

Improved link section

---

.github/workflows/build.yml
doc/changes/changes_3.8.0.md
doc/spec/design.md
doc/spec/system_requirements.md
reporter/html/src/main/java/org/itsallcode/openfasttrace/report/html/view/html/HtmlReportSummary.java
reporter/html/src/main/java/org/itsallcode/openfasttrace/report/html/view/html/HtmlSection.java
reporter/html/src/main/java/org/itsallcode/openfasttrace/report/html/view/html/HtmlSpecificationItem.java
reporter/html/src/main/java/org/itsallcode/openfasttrace/report/html/view/html/HtmlView.java
reporter/html/src/main/java/org/itsallcode/openfasttrace/report/html/view/html/HtmlViewFactory.java
reporter/html/src/main/java/org/itsallcode/openfasttrace/report/html/view/html/MarkdownSpanConverter.java
reporter/html/src/main/java/org/itsallcode/openfasttrace/report/html/view/html/OriginLinkFormatter.java
reporter/html/src/test/java/org/itsallcode/openfasttrace/report/html/view/html/AbstractTestHtmlRenderer.java
reporter/html/src/test/java/org/itsallcode/openfasttrace/report/html/view/html/MarkdownSpanConverterTest.java
reporter/html/src/test/java/org/itsallcode/openfasttrace/report/html/view/html/TestHtmlReportSummary.java
reporter/html/src/test/java/org/itsallcode/openfasttrace/report/html/view/html/TestHtmlSpecificationItem.java

#303: Escape special characters in HTML

---

doc/changes/changes_3.8.0.md
doc/user_guide.md
importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java
importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterFactory.java

#394: Import tags also from `.yml` files

---

README.md
api/src/main/java/org/itsallcode/openfasttrace/api/importer/input/RealFileInput.java
api/src/test/java/org/itsallcode/openfasttrace/api/importer/input/TestRealFileInput.java
doc/changes/changes_3.8.0.md
doc/developer_guide.md
importer/zip/src/test/java/org/itsallcode/openfasttrace/importer/zip/ITZipFileImporter.java
importer/zip/src/test/java/org/itsallcode/openfasttrace/importer/zip/input/TestZipEntryInput.java
parent/pom.xml
product/src/test/resources/example/src/invalid_encoding.c

#391: Fix reading files with invalid encoding

---

doc/user_guide.md

#393 Add Maven & Gradle plugins to user guide

---

.github/workflows/build.yml
api/pom.xml
core/pom.xml
doc/changes/changes.md
doc/changes/changes_3.8.1.md
doc/developer_guide.md
exporter/common/pom.xml
exporter/specobject/pom.xml
importer/markdown/pom.xml
importer/specobject/pom.xml
importer/tag/pom.xml
importer/xmlparser/pom.xml
importer/zip/pom.xml
parent/pom.xml
pom.xml
product/pom.xml
reporter/aspec/pom.xml
reporter/html/pom.xml
reporter/plaintext/pom.xml
testutil/pom.xml

#399: Configure and verify reproducible build

---

.github/workflows/broken_links_checker.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.vscode/settings.json
importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporter.java

Refactor TagImporter unit test to use @ParameterizedTest

---

.gitignore
core/src/test/java/org/itsallcode/openfasttrace/core/matcher/SpecificationItemIdMatcher.java
doc/developer_guide.md
parent/pom.xml
product/src/test/java/org/itsallcode/openfasttrace/cli/TestCliStarter.java
reporter/aspec/src/test/java/org/itsallcode/openfasttrace/report/aspec/TestASpecReport.java
testutil/pom.xml
testutil/src/main/java/module-info.java
testutil/src/main/java/org/itsallcode/openfasttrace/testutil/matcher/StringRegexpMatcher.java
testutil/src/test/java/org/itsallcode/openfasttrace/testutil/matcher/StringRegexpMatcherTest.java

This upgrades hamcrest from 1.3 to 2.2

Upgrade hamcrest

---

.github/workflows/build.yml
.github/workflows/github_release.sh
.github/workflows/release.yml
.github/workflows/run_shellcheck.sh
.vscode/extensions.json
doc/changes/changes_4.0.0.md
doc/developer_guide.md
oft
parent/pom.xml

Add release workflow

---

README.md
api/src/main/java/org/itsallcode/openfasttrace/api/core/SpecificationItemId.java
api/src/test/java/org/itsallcode/openfasttrace/api/core/TestSpecificationItemId.java
doc/changes/changes.md
doc/changes/changes_4.0.1.md
doc/user_guide.md
parent/pom.xml
pom.xml
testutil/src/main/java/org/itsallcode/openfasttrace/testutil/importer/lightweightmarkup/AbstractLightWeightMarkupImporterTest.java

#417: Allow numbers after dots in specificaiton item names

---

README.md
doc/changes/changes.md
doc/changes/changes_4.0.2.md
parent/pom.xml
reporter/html/src/main/resources/css/report.css

Fix issue 420 about hidden section text under navbar

---

core/src/main/java/org/itsallcode/openfasttrace/core/cli/CommandLineInterpreter.java
core/src/test/java/org/itsallcode/openfasttrace/core/cli/TestCommandLineInterpreter.java
doc/changes/changes_4.0.2.md
doc/user_guide.md
importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/TestMarkdownImporter.java
importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/TestMarkdownMarkupImporter.java
testutil/src/main/java/org/itsallcode/openfasttrace/testutil/importer/lightweightmarkup/AbstractLightWeightMarkupImporterTest.java

#419 Fix inconsistencies in documentation and error messages
