- .travis.yml
- launch/Openfasttrack - Run all tests.launch
- pom.xml
- src/main/java/openfasttrack/core/SpecificationItem.java
- src/main/java/openfasttrack/core/SpecificationItemId.java
- src/main/java/openfasttrack/importer/ImportEventListener.java
- src/main/java/openfasttrack/importer/ImporterException.java
- src/main/java/openfasttrack/importer/SpecificationItemListBuilder.java
- src/main/java/openfasttrack/importer/markdown/MarkdownImporter.java
- src/main/java/openfasttrack/importer/specobject/ImportHelper.java
- src/main/java/openfasttrack/importer/specobject/SingleSpecobjectImportHelper.java
- src/main/java/openfasttrack/importer/specobject/SpecobjectImporter.java
- src/test/java/openfasttrack/core/TestSpecificationItem.java
- src/test/java/openfasttrack/importer/TestSpecificationItemListBuilder.java
- src/test/java/openfasttrack/importer/markdown/TestImportMarkdown.java
- src/test/java/openfasttrack/importer/specobject/SpecobjectImporterTest.java
- src/test/resources/logging.properties
- src/test/resources/specobject/single-specobject.xml
Refactoring of `SpecificationItemListBuilder`: all specifying id after foundNewSpecificationItem() was called. This allows composing the id from name, revision and doctype.
> Specobject importer

- doc/system_requirements.md
- src/main/java/openfasttrack/core/LinkStatus.java
- src/main/java/openfasttrack/core/LinkedSpecificationItem.java
- src/main/java/openfasttrack/report/PlainTextReport.java
- src/test/java/openfasttrack/core/TestLinkedSpecificationItem.java
- src/test/java/openfasttrack/report/TestPlainTextReport.java
This is needed to determine if an item is defect or not.
> #17: Defect status now considers duplicates and all kinds of bad links.

- src/main/java/org/itsallcode/openfasttrace/importer/legacytag/LegacyTagImporterConfig.java
- src/main/java/org/itsallcode/openfasttrace/importer/legacytag/LegacyTagImporterFactory.java
- src/main/java/org/itsallcode/openfasttrace/importer/legacytag/PathConfig.java
- src/test/java/org/itsallcode/openfasttrace/importer/legacytag/TestLegacyTagImporterFactory.java
This is required for gradle plugin configuration
> Support relative paths for legacy tag importer

- .markdownlint.json
- README.md
- doc/design.md
- doc/system_requirements.md
- model/actors/developer.plantuml
- model/actors/quality_engineer.plantuml
- model/components/continuous_integration.plantuml
- model/components/system.plantuml
- model/diagrams/component/context.plantuml
- model/diagrams/component/specification_item_import.plantuml
- src/main/java/org/itsallcode/openfasttrace/Converter.java
- src/main/java/org/itsallcode/openfasttrace/Reporter.java
- src/main/java/org/itsallcode/openfasttrace/importer/legacytag/LegacyTagImporter.java
- src/main/java/org/itsallcode/openfasttrace/importer/legacytag/LegacyTagImporterFactory.java
- src/main/java/org/itsallcode/openfasttrace/importer/legacytag/PathConfig.java
- src/main/java/org/itsallcode/openfasttrace/importer/legacytag/config/DescribedPathMatcher.java
- src/main/java/org/itsallcode/openfasttrace/importer/legacytag/config/LegacyTagImporterConfig.java
- src/main/java/org/itsallcode/openfasttrace/importer/legacytag/config/PathConfig.java
- src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporter.java
- src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java
- src/main/java/org/itsallcode/openfasttrace/mode/AbstractMode.java
- src/test/java/org/itsallcode/openfasttrace/importer/legacytag/TestLegacyTagImporter.java
- src/test/java/org/itsallcode/openfasttrace/importer/legacytag/TestLegacyTagImporterFactory.java
- src/test/java/org/itsallcode/openfasttrace/importer/legacytag/TestPathConfig.java
- src/test/java/org/itsallcode/openfasttrace/importer/legacytag/config/DescribedPathMatcherTest.java
- src/test/java/org/itsallcode/openfasttrace/importer/legacytag/config/TestPathConfig.java
- src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporter.java
- src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterFactory.java
- src/test/java/org/itsallcode/openfasttrace/testutil/OsDetector.java
- src/test/resources/logging.properties
Allow configuring a list of paths instead of pattern
> Refactor path config

- src/main/java/org/itsallcode/openfasttrace/core/SpecificationItem.java
- src/main/java/org/itsallcode/openfasttrace/core/SpecificationItemId.java
- src/main/java/org/itsallcode/openfasttrace/exporter/specobject/SpecobjectExporter.java
- src/main/java/org/itsallcode/openfasttrace/importer/SpecificationListBuilder.java
- src/main/java/org/itsallcode/openfasttrace/importer/specobject/handler/SingleSpecObjectsHandlerBuilder.java
- src/main/java/org/itsallcode/openfasttrace/importer/specobject/handler/SpecObjectsHandlerBuilder.java
- src/test/java/org/itsallcode/openfasttrace/exporter/specobject/TestSpecobjectExporter.java
- src/test/java/org/itsallcode/openfasttrace/importer/input/StreamInput.java
- src/test/java/org/itsallcode/openfasttrace/importer/specobject/TestSpecobjectImportExport.java
* Fix location when importing specobjects
* Fix exported covers name
> Specobject bugfixes

- README.md
- doc/developer_guide.md
Links to the contribution guide were broken at two places.
> Fixed links to contribution guide

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
The AdoptOpenJDK has been discontinued Since July 2021. When using Zulu you get all the latest updated builds (TCK tested) for all versions of OpenJDK. 🥇
> Using Temurin builds of OpenJDK in GH actions

- doc/CHANGELOG.md
- doc/user_guide.md
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java
- importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterFactory.java
- parent/pom.xml
> #296, #294: Support PlantUML and Go with TagImporter

- doc/CHANGELOG.md
- doc/user_guide.md
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java
- importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterFactory.java
For C# files with `.cs` extension are now supported additionally to `.c#` extension. Closess #326.
> #326: Import files with `.cs` extension

- doc/user_guide.md
I felt that the user guide did not explain well enough how to use keywords in specification items, which led me to open issue #325. After examining the source code I gained a better understanding on specification items and this is my attempt to explain them a bit better, especially the available keywords.
> Extended user_guide.md to explain keywords in specification items

- .github/workflows/build.yml
- api/src/main/java/org/itsallcode/openfasttrace/api/ColorScheme.java
- api/src/main/java/org/itsallcode/openfasttrace/api/ReportSettings.java
- core/src/main/java/org/itsallcode/openfasttrace/core/cli/ArgumentValidator.java
- core/src/main/java/org/itsallcode/openfasttrace/core/cli/CliArguments.java
- core/src/main/java/org/itsallcode/openfasttrace/core/cli/commands/TraceCommand.java
- core/src/main/resources/usage.txt
- core/src/test/java/org/itsallcode/openfasttrace/core/cli/TestArgumentValidator.java
- core/src/test/java/org/itsallcode/openfasttrace/core/cli/TestCliArguments.java
- doc/spec/design.md
- doc/spec/system_requirements.md
- doc/user_guide.md
- importer/specobject/src/main/java/org/itsallcode/openfasttrace/importer/specobject/handler/SpecDocumentHandlerBuilder.java
- product/src/test/java/org/itsallcode/openfasttrace/cli/TestCliStarter.java
- reporter/plaintext/src/main/java/org/itsallcode/openfasttrace/report/plaintext/AnsiSequence.java
- reporter/plaintext/src/main/java/org/itsallcode/openfasttrace/report/plaintext/ConsoleColorFormatter.java
- reporter/plaintext/src/main/java/org/itsallcode/openfasttrace/report/plaintext/MonochromeTextFormatter.java
- reporter/plaintext/src/main/java/org/itsallcode/openfasttrace/report/plaintext/NullTextFormatter.java
- reporter/plaintext/src/main/java/org/itsallcode/openfasttrace/report/plaintext/PlainTextReport.java
- reporter/plaintext/src/main/java/org/itsallcode/openfasttrace/report/plaintext/TextFormatter.java
- reporter/plaintext/src/main/java/org/itsallcode/openfasttrace/report/plaintext/TextFormatterFactory.java
- reporter/plaintext/src/test/java/org/itsallcode/openfasttrace/report/plaintext/AnsiSequenceTest.java
- reporter/plaintext/src/test/java/org/itsallcode/openfasttrace/report/plaintext/ConsoleColorFormatterTest.java
- reporter/plaintext/src/test/java/org/itsallcode/openfasttrace/report/plaintext/TestNullTextFormatter.java
- reporter/plaintext/src/test/java/org/itsallcode/openfasttrace/report/plaintext/TestPlainTextReport.java
- reporter/plaintext/src/test/java/org/itsallcode/openfasttrace/report/plaintext/TestTextFormatterFactory.java
- testutil/pom.xml
- testutil/src/main/java/module-info.java
> #338: Colored console report

- api/src/main/java/org/itsallcode/openfasttrace/api/core/SpecificationItemId.java
- api/src/main/java/org/itsallcode/openfasttrace/api/core/TracedLink.java
- core/src/test/java/org/itsallcode/openfasttrace/core/matcher/SpecificationItemIdMatcher.java
- core/src/test/java/org/itsallcode/openfasttrace/core/matcher/SpecificationItemMatcher.java
- doc/changes/changes.md
- doc/changes/changes_3.7.2.md
- doc/developer_guide.md
- importer/markdown/src/main/java/org/itsallcode/openfasttrace/importer/markdown/MarkdownImporter.java
- importer/markdown/src/main/java/org/itsallcode/openfasttrace/importer/markdown/MdPattern.java
- importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/ITMarkdownImporter.java
- importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/TestMarkdownImporter.java
- importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporter.java
- parent/pom.xml
- product/src/test/java/org/itsallcode/openfasttrace/exporter/specobject/TestSpecobjectExportImport.java
- product/src/test/java/org/itsallcode/openfasttrace/importer/specobject/TestSpecobjectImportExport.java
Closes #364
This PR addresses issue 364: https://github.com/itsallcode/openfasttrace/issues/364
I noticed that "Tags" lists behave the same way, so I updated them as well.
> Ignore spaces after items in "Needs:" and "Tags:" lists

- api/src/main/java/org/itsallcode/openfasttrace/api/core/SpecificationItemId.java
- doc/changes/changes_3.8.0.md
- doc/spec/design.md
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/ChecksumCalculator.java
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/LineReader.java
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/LongTagImportingLineConsumer.java
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/RegexLineConsumer.java
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/ShortTagImportingLineConsumer.java
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporter.java
- importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporter.java
- product/src/test/java/org/itsallcode/openfasttrace/ITestSelfTrace.java
> #379: Allow specifying revision for tags

- README.md
- doc/changes/changes.md
- doc/changes/changes_4.1.0.md
- doc/developer_guide.md
- doc/user_guide.md
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java
- importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterFactory.java
- parent/pom.xml
Added "feature" to the list of supported file extensions so that
the standard Tag importer can now extract Tags from comments in
"feature" files as used by Gherkin.
This addresses #425
Closes #425
> Add support for reading Tags from Gherkin feature files

- doc/changes/changes.md
- doc/changes/changes_4.2.0.md
- importer/lightweightmarkup/src/main/java/org/itsallcode/openfasttrace/importer/lightweightmarkup/statemachine/LineParserState.java
- importer/markdown/src/main/java/org/itsallcode/openfasttrace/importer/markdown/MarkdownImporter.java
- importer/markdown/src/main/java/org/itsallcode/openfasttrace/importer/markdown/MdPattern.java
- importer/markdown/src/test/java/org/itsallcode/openfasttrace/importer/markdown/TestMarkdownMarkupImporter.java
> #280: Ignore requirement in Markdown code blocks

- .github/workflows/build.yml
- core/src/test/java/org/itsallcode/openfasttrace/core/cli/TestCliStarter.java
- doc/changes/changes_4.2.0.md
- parent/pom.xml
- product/src/test/java/org/itsallcode/openfasttrace/cli/ITestCliWithFilter.java
- product/src/test/java/org/itsallcode/openfasttrace/cli/TestCliExit.java
- product/src/test/java/org/itsallcode/openfasttrace/cli/TestCliStarter.java
Update build and test dependencies to the latest versions
> Upgrade dependencies

- doc/changes/changes_4.2.0.md
- doc/user_guide.md
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java
- importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterFactory.java
Add support for ".toml" files in the tag importer factory.
Closes #440.
> #440: Support TOML files in tag importer

- importer/markdown/src/main/java/org/itsallcode/openfasttrace/importer/markdown/MdPattern.java
- importer/restructuredtext/src/main/java/org/itsallcode/openfasttrace/importer/restructuredtext/RstPattern.java
Both Restructured and Markdown importer at the moment do not support the ItemStatus rejected. This change extends the importer to also accept "rejected" as status.
> Status rejected for Restructured and Markdown importer.

- doc/changes/changes_4.2.0.md
- doc/user_guide.md
- importer/tag/src/main/java/org/itsallcode/openfasttrace/importer/tag/TagImporterFactory.java
- importer/tag/src/test/java/org/itsallcode/openfasttrace/importer/tag/TestTagImporterFactory.java
In addition to `.js`, modern javascript may use `.mjs`, `.cjs`, and `.ejs`. This request adds those extensions to `TagImporterFactory.java` and `TestTagImporterFactory.java`
[Node Doc](https://nodejs.org/docs/latest-v20.x/api/modules.html#enabling)
> add modern javascript extension support

- .github/workflows/release.yml
- doc/changes/changes_4.2.0.md
- parent/pom.xml
- testutil/pom.xml
> 452: Migrate to central publishing
